import React,{useState} from 'react';
import {RichNarrative,ReportSection,EvidenceChart,DataComponent,DataTable,Dropdown,SectionHeader,useDataApp} from '../../data-app-public.jsx';
import './review.css';
const labels={clean_regime:'Clean regime: Apr 28–Sep 27',all_published:'Full published season',FIRE:'FIRE',LEAN:'LEAN',ALL:'FIRE + LEAN',month:'Month',week:'ISO week',pitcher_team:'Pitcher team',opponent_team:'Opponent',side:'Side',monthly:'Month',weekly:'ISO week',opponent:'Opponent',line:'Betting line'};
const col=(field,label)=>({field,label,renderCell:v=>typeof v==='number'?Number.isInteger(v)?v:v.toFixed(2):v});
function Table({id,query,rows,columns,title}){return <DataComponent id={id} queryId={query} kind="table" title={title} sourceRows={rows} displayRows={rows}><DataTable rows={rows} columns={columns}/></DataComponent>}
function Prose({id,query,rows,text}){return <ReportSection id={id} queryId={query} sourceRows={rows} title={id.replaceAll("-"," ")} showHeading={false}><RichNarrative id={`${id}-text`} value={text}/></ReportSection>}
export function ReportContent(){
const {reviewedRows}=useDataApp();const [scope,S]=useState('clean_regime'),[tier,T]=useState('FIRE'),[cut,C]=useState('month'),[pc,P]=useState('monthly');
const rq=`${scope}_${tier}_${cut}`,rr=reviewedRows(rq),pq=`projection_${pc}`,pr=reviewedRows(pq),arch=reviewedRows('architecture'),cal=reviewedRows('calibration_tracked_side'),mov=reviewedRows('price_movement'),games=reviewedRows('pitcher_game_comparison');
const drop=(label,value,choices,onChange)=><Dropdown label={label} showLabel value={value} choices={choices} choiceLabels={labels} onChange={onChange}/>;
return <article className="report-content bbe-review">
<header className="report-hero"><RichNarrative id="hero" value={'# 2026 review → a better 2027\n\n**Keep the core app. Simplify operations. Rebuild the evidence for betting.**\n\nSeason evidence through September 27 · Reviewed October 1, 2026 · Offline only'}/></header>
<Prose id="summary" query="architecture" rows={arch} text={'## The decision in three parts\n\n**Structure: workable.** The 11 Render entries were eight operational scheduled jobs, two research jobs and a retired worker. Six operational jobs are a reasonable future target after testing; there is no evidence we need more capacity.\n\n**Results: the clean-period FIRE record lost 45.03u.** June and May generated 80.6% of that net loss. The full-season FIRE result was −35.30u, so mixing early and clean regimes changes the story. These are published picks at flat 1u risk, not your actual betting account.\n\n**Model: accurate season average, weaker individual forecasts.** Across 2,744 pitcher games, model error averaged 1.88 Ks versus 1.78 for the posted line. Selected research probabilities were around 60–62%, but outcomes were around 50%.\n\nAll services remain suspended. PropLine is canceled per your instruction; TheRundown is the future odds source. No restart, provider pull, grading or live model change is part of this review.'}/>
<Prose id="structure" query="architecture" rows={arch} text={'## 1 · Preserve the core; reduce operational complexity\n\nThe pipeline → stored artifacts → static dashboard separation is sound. Keep preview, grading, full run, refresh, live evidence/lock production and lock publication as distinct responsibilities. Consolidating the three refresh schedules could reduce eight operational jobs to six. Keep research jobs on demand and BoltOdds retired.\n\nBefore restarting, remove forced TheRundown + PropLine selection and key-triggered PropLine/The Odds API fallbacks. Prevent stale PropLine state from entering official prices. TheRundown movement collection already exists, but future cadence and quota need review. Preserve the critical lock path, reconcile deployed code versions, and decide whether grading may automatically recalibrate the model.\n\nThis is an architecture recommendation, not a deployed refactor. Scheduled job count alone does not establish cost, redundancy or overload.'}/>
<EvidenceChart id="architecture-chart" queryId="architecture" title="Render service roles at shutdown" rows={arch} sourceRows={arch} spec={{type:'horizontalBar',x:'role',y:'jobs'}} height={240}/>
<Prose id="results-intro" query={rq} rows={rr} text={'## 2 · Where the published picks lost\n\nStart with the clean regime and FIRE. Change the population and breakdown below to inspect every month, week, pitcher team, opponent and side. Published-verdict classification matches the season freeze; using locked verdict instead changes FIRE to −43.31u through two selections.\n\nJune lost 21.06u and May lost 15.24u. UNDER lost 34.30u across 316 settled FIRE picks; OVER lost 10.72u across 481. Ten of 22 weeks were positive. Team results are exploratory: every clean FIRE team group contains fewer than 50 settled picks. Do not turn the worst teams into exclusion rules from this sample.'}/>
<SectionHeader id="results-controls" title="Published results explorer" filters={<>{drop('Period',scope,['clean_regime','all_published'],S)}{drop('Tier',tier,['FIRE','LEAN','ALL'],T)}{drop('Breakdown',cut,['month','week','pitcher_team','opponent_team','side'],C)}</>}/>
<EvidenceChart id="results-chart" queryId={rq} title="Net units · flat 1u risk" rows={rr} sourceRows={rr} spec={{type:cut.includes("team")?"horizontalBar":"bar",x:'group',y:'pnl_units',valueDecimals:2}} height={cut.includes("team")?1000:330}/>
<Table id="results-table" query={rq} rows={rr} title="Results and sample size" columns={[col('group','Group'),col('settled','Settled'),col('wins','Wins'),col('losses','Losses'),col('voids','Voids'),col('pnl_units','Net units'),col('roi_pct','ROI %'),col('win_pct','Win %')]}/>
<Prose id="projection-intro" query={pq} rows={pr} text={'## 3 · Compare the projection, betting line and actual Ks\n\nThe model averaged 4.97 Ks against 4.93 actual: only +0.04 Ks of overall bias. That masks game-level error. Model MAE was 1.876 versus 1.785 for the posted line; the line was closer in all six monthly slices and 19 of 22 weeks. The line is a market benchmark, not literally an expected-value projection.\n\nShrinking the model 25% toward the line reduced MAE to 1.825; 35% reduced it to 1.808 on this full descriptive sample. Existing retained shadow comparisons also improve projection error, but none establishes a profitable would-bet strategy. Use chronological holdouts and explicit prices/stakes before promotion.'}/>
<SectionHeader id="projection-controls" title="Projection accuracy explorer" filters={drop('Breakdown',pc,['monthly','weekly','pitcher_team','opponent','line'],P)}/>
<EvidenceChart id="projection-chart" queryId={pq} title="Average absolute error in Ks · lower is better" rows={pr} sourceRows={pr} spec={{type:["pitcher_team","opponent"].includes(pc)?"horizontalBar":"bar",x:'slice',y:'model_mae',fields:['model_mae','line_mae'],stackable:false,valueDecimals:2}} height={["pitcher_team","opponent"].includes(pc)?1100:330}/>
<Table id="projection-table" query={pq} rows={pr} title="Projection and market comparison" columns={[col('slice','Group'),col('n','Games'),col('actual_mean','Actual Ks'),col('model_mean','Model Ks'),col('line_mean','Line'),col('model_bias','Model bias'),col('model_mae','Model MAE'),col('line_mae','Line MAE')]}/>
<Prose id="calibration-intro" query="calibration_tracked_side" rows={cal} text={'### Confidence needs more work than the season average\n\nTracked research OVER forecasts averaged 59.55% against 49.69% realized wins. UNDER averaged 61.68% against 49.97%. No-vig market probabilities were much nearer the realized rates. The gap survives removing 38 changed-line matches; it is not explained by pushes or reversed result labels.\n\nThese are 2,893 tracked research side rows, including both sides on 149 pitcher dates—not 2,893 independent bets. The probabilities come from final artifacts, not assured original decision-time forecasts. Reconstruct frozen decision-time confidence before attributing this gap to the production selector.'}/>
<Table id="calibration-table" query="calibration_tracked_side" rows={cal.map(r=>({...r,forecast_pct:r.model_win_prob_mean*100,actual_pct:r.win_rate*100,market_pct:r.no_vig_side_probability_mean*100}))} title="Research confidence versus outcomes" columns={[col('slice','Side'),col('n','Rows'),col('forecast_pct','Model %'),col('actual_pct','Actual %'),col('market_pct','Market no-vig %'),col('model_win_prob_brier','Model Brier'),col('no_vig_side_probability_brier','Market Brier')]}/>
<Prose id="movement-intro" query="price_movement" rows={mov} text={'## 4 · Movement is promising evidence, with incomplete timing\n\nResearch rows whose opening-to-current price moved with the selected side won 54.95% and were approximately flat (−0.05u attached PnL). Against-side movement won 46.70% and lost 43.88u; unchanged prices won 48.55% and lost 142.06u. These are descriptive research populations, not the published accounting total.\n\nThis is retrospective price movement, not a tested signal available at bet time. The frozen rows lack season-wide line-movement and agreement labels. Price thresholds can misclassify American-odds sign crossings; exact book, line and pregame timing are incomplete. The fully attributed historical close-price receipt covers only 33 targets across two days. A season-wide executable CLV claim is not supported. Preserve the evidence and test movement on timestamped same-market observations before using it to filter picks.'}/>
<Table id="movement-table" query="price_movement" rows={mov} title="Opening-to-current price movement" columns={[col('slice','Movement'),col('n','Rows'),col('wins','Wins'),col('win_rate','Win rate (0–1)'),col('history_pnl_rows','PnL rows'),col('history_pnl_sum','Attached units')]}/>
<Prose id="games-intro" query="pitcher_game_comparison" rows={games} text={'## 5 · Inspect individual pitcher games\n\nSearch by pitcher, date or team. Each row is one pitcher-date, with projection, posted line and actual result. Error is forecast minus actual. This is the frozen final-artifact research population; it is not an accepted-bet ledger.'}/>
<Table id="games-table" query="pitcher_game_comparison" rows={games} title="All 2,744 pitcher games" columns={[col('date','Date'),col('pitcher','Pitcher'),col('team','Team'),col('opponent','Opponent'),col('projected_ks','Projected Ks'),col('line','Line'),col('actual_ks','Actual Ks'),col('model_error','Model error'),col('line_error','Line error')]}/>
<Prose id="decisions" query="architecture" rows={arch} text={'## 6 · The work that earns a 2027 restart\n\n1. **Make TheRundown-only behavior explicit.** Remove canceled-provider paths, verify supported books and quota, align deployed code, and test locked picks without restarting services.\n2. **Reconstruct original decisions.** Join timestamped forecast, line, price, book, verdict and result. Reconcile accepted bets and actual stakes separately; the account loss remains unresolved.\n3. **Test probability calibration and market shrink.** Compare current, market-only and shrink challengers with explicit would-bet rules, juice, turnover and flat/stated stake policies. Separate model quality from selection quality.\n4. **Evaluate movement without hindsight.** Use same-book, same-line, pregame checkpoints. Quantify missingness before interpreting performance.\n5. **Set a frozen-model canary plan.** Use a genuinely future evaluation window, predeclared sample and loss limits, and a separate approval to restart. 2026 has already informed hypothesis selection.\n\n**Evidence boundaries.** Published history was read once from stored artifacts at October 1 15:08 UTC. Its hash differs from the original 13:17 freeze receipt, but the headline totals reconcile and all 2,777 clean settled picks match research. All settled published payouts match flat 1u risk. No provider calls, new grades, calibration, live writes or deployments were used to build this report. Supporting reports, source hashes and reproducible tables are saved in the BBE repository.'}/>
</article>}
