"""Canonical MLB team-name to code mapping used by pipeline data files."""

TEAM_NAME_TO_CODE = {
    "Los Angeles Angels": "LAA",
    "Anaheim Angels": "LAA",
    "Los Angeles Angels of Anaheim": "LAA",
    "Baltimore Orioles": "BAL",
    "Boston Red Sox": "BOS",
    "Chicago White Sox": "CHW",
    "Cleveland Guardians": "CLE",
    "Cleveland Indians": "CLE",
    "Detroit Tigers": "DET",
    "Kansas City Royals": "KC",
    "Minnesota Twins": "MIN",
    "New York Yankees": "NYY",
    "Athletics": "ATH",
    "Oakland Athletics": "ATH",
    "Seattle Mariners": "SEA",
    "Tampa Bay Rays": "TB",
    "Tampa Bay Devil Rays": "TB",
    "Texas Rangers": "TEX",
    "Toronto Blue Jays": "TOR",
    "Arizona Diamondbacks": "ARI",
    "Arizona D-backs": "ARI",
    "Atlanta Braves": "ATL",
    "Chicago Cubs": "CHC",
    "Cincinnati Reds": "CIN",
    "Colorado Rockies": "COL",
    "Miami Marlins": "MIA",
    "Florida Marlins": "MIA",
    "Houston Astros": "HOU",
    "Los Angeles Dodgers": "LAD",
    "Milwaukee Brewers": "MIL",
    "Washington Nationals": "WSH",
    "New York Mets": "NYM",
    "Philadelphia Phillies": "PHI",
    "Pittsburgh Pirates": "PIT",
    "St. Louis Cardinals": "STL",
    "San Diego Padres": "SD",
    "San Francisco Giants": "SF",
}

TEAM_CODES = frozenset(TEAM_NAME_TO_CODE.values())
